---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.serviceInstance.nameOverride }}-config"
  annotations:
    "helm.sh/hook-weight": "-5"
data:
  NODE_ENV: "development"
  APP_PORT: {{ .Values.applicationPort | quote }}
  DB_NAME: {{ .Values.postgresql.postgresqlDatabase | quote }}
  DB_PORT: {{ .Values.postgresql.service.port | quote }}
  DB_HOST: {{ include "postgresql.fullname" . }}
  KAFKA_BROKER: {{ .Values.kafka.broker | quote }}
  KAFKA_PORT: {{ .Values.kafka.port | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.serviceInstance.nameOverride }}-secret"
  annotations:
    "helm.sh/hook-weight": "-10"
type: Opaque
data:
  DATABASE_URI: {{ printf "postgresql+psycopg2://%s:%s@%s:%s/%s"
                    .Values.postgresql.postgresqlUsername
                    .Values.postgresql.postgresqlPassword (include "postgresql.fullname" .)
                    .Values.postgresql.service.port
                    .Values.postgresql.postgresqlDatabase |
                    b64enc | quote }}
  DB_USER: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  DB_PSWD: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}



